Respin browsers tags for xvfb.

diff --git a/3.6/browsers/Dockerfile b/3.6/browsers/Dockerfile
--- a/3.6/browsers/Dockerfile
+++ b/3.6/browsers/Dockerfile
@@ -11,13 +11,23 @@ RUN curl -sSL -o selenium-server-standalone-${SELENIUM_VER}.jar "https://seleniu
     rm selenium-server-standalone-${SELENIUM_VER}.jar
 
 RUN sudo apt-get update && \
+
+    # Install Java only if it's not already available
+    # Java is installed for Selenium
+    if ! command -v java > /dev/null; then \
+        echo "Java not found in parent image, installing..." && \
+        sudo apt-get install -y --no-install-recommends --no-upgrade openjdk-11-jre; \
+    fi && \
+
     # Firefox deps
     sudo apt-get install -y --no-install-recommends --no-upgrade \
 		libdbus-glib-1-2 \
 		libgtk-3-dev \
 		libxt6 \
 	&& \
+
     # Google Chrome deps
+	# Some of these packages should be pulled into their own section
     sudo apt-get install -y --no-install-recommends --no-upgrade \
         fonts-liberation \
         libappindicator3-1 \
@@ -32,8 +42,22 @@ RUN sudo apt-get update && \
         libpango-1.0-0 \
         libpangocairo-1.0-0 \
         libxcursor1 \
-        # java for selenium
-        openjdk-11-jre \
+		libxss1 \
         xdg-utils \
+		xvfb \
 	&& \
 	sudo rm -rf /var/lib/apt/lists/*
+
+# Below is setup to allow xvfb to start when the container starts up.
+# The label in particular allows this image to override what CircleCI does
+# when booting the image.
+LABEL com.circleci.preserve-entrypoint=true
+ENV DISPLAY=":99"
+#RUN	printf '#!/bin/sh\nXvfb :99 -screen 0 1280x1024x24 &\nexec "$@"\n' > /tmp/entrypoint && \
+#	chmod +x /tmp/entrypoint && \
+#	sudo mv /tmp/entrypoint /docker-entrypoint.sh
+RUN	printf '#!/bin/sh\nXvfb :99 -screen 0 1280x1024x24 &\nexec "$@"\n' | sudo tee /docker-entrypoint.sh && \
+	sudo chmod +x /docker-entrypoint.sh
+
+ENTRYPOINT ["/docker-entrypoint.sh"]
+CMD ["/bin/sh"]
